### ISSUE TITLE
How to create a scoped method?

### ISSUE THREAD

**Issue by dcangulo** [ammarahm-ed/react-native-simple-jsi#18]
This code:
```c
jsiRuntime.global().setProperty(jsiRuntime, "helloWorld", move(helloWorld));
```

Gives us:
```js
global.helloWorld();
```

What if I want to have it scoped to not fill the global?

Eg.
```js
global.MyModule.helloWorld();
```

Or I should just do:
```js
global.MyModule = { helloWorld: global.helloWorld };
```

Which I think defeats the purpose since it is still defined in `global`.

Something like:
```js
global.ExpoModules.ExpoRandom.getRandomBase64String
```

from Expo.

https://github.com/LinusU/react-native-get-random-values/blob/master/index.js#L34

I'm not sure how they did it, the repo is not yet updated or I am looking at the wrong code.

https://github.com/expo/expo/tree/sdk-45/packages/expo-random

Any ideas?

**Comment by ammarahm-ed** [comment]
That would be as simple as:

```c#
// 1. Create a global object
jsi::Object module = jsi::Object(runtime);

// 2. Register your function with the object
module.setProperty(runtime, "helloWorld", move(helloWorld));

// 3. Finally register the global object you created.
runtime.global().setProperty(runtime "MyModule", move(module));
```

> Which I think defeats the purpose since it is still defined in global

In a way yes but that's the only way to do this for now. Some more abstraction can be created. For example, registering the module with an existing global object in the JS runtime similar to how Expo does. But as long as you know what you put in the global space, it's alright.
