### ISSUE TITLE
In Debug with Chrome，global.helloWorld is not a function

### ISSUE THREAD

**Issue by coder-log666** [ammarahm-ed/react-native-simple-jsi#2]
I create a new react-native procject
```shell
npx react-native init jsiDemo
```
and drag `SimpleJsi.h` `SimpleJsi.mm` `example.h` `example.cpp`  into ios project. and modify `app.js` 
```js
React.useEffect(() => {
    setResult(global.helloWorld());
  }, []);
```
everything feels good. 
![image](https://user-images.githubusercontent.com/77562437/129451336-519bea2a-0e99-4fc4-aab0-0bf6280a01f8.png)

but  when I Debug with Chrome there is a error like this:
![image](https://user-images.githubusercontent.com/77562437/129451295-b8605f07-8417-438b-80fc-1a63b3a29ba7.png)

can you help me?

**Comment by ammarahm-ed** [comment]
> I create a new react-native procject
> ```shell
> npx react-native init jsiDemo
> ```
> and drag `SimpleJsi.h` `SimpleJsi.mm` `example.h` `example.cpp`  into ios project. and modify `app.js` 
> ```js
> React.useEffect(() => {
>     setResult(global.helloWorld());
>   }, []);
> ```
> everything feels good. 
> ![image](https://user-images.githubusercontent.com/77562437/129451336-519bea2a-0e99-4fc4-aab0-0bf6280a01f8.png)
> 
> but  when I Debug with Chrome there is a error like this:
> ![image](https://user-images.githubusercontent.com/77562437/129451295-b8605f07-8417-438b-80fc-1a63b3a29ba7.png)
> 
> can you help me? 
> 
> 

There is no support for chrome debugger in JSI.
