### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/libreactnativeutilsjni.so'

### ISSUE THREAD

**Issue by blowback** [ammarahm-ed/react-native-simple-jsi#4]
Trying to build the example app for android, I get the above build failure. A link is mentioned https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake but actually see here https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets - none of this appears to be relevant tho.

**Comment by ammarahm-ed** [comment]
Use this in `app/build.gradle` in example app.

```
packagingOptions {
    pickFirst '**/*.so'
}
```

**Comment by blowback** [comment]
That sorted it! Many thanks.

**Comment by ammarahm-ed** [comment]
@blowback  I have fixed this on master. If you pull again, you don't need to make that change in example app.

**Comment by blowback** [comment]
FYI fix on master didn't work for me, I still had to make the above change to the example's app/build.gradle
